import type { Metadata } from "next";
import { Inter_Tight, Anton, Lobster, Great_Vibes, Style_Script, Calistoga } from "next/font/google";
import "./globals.css";

const inter = Inter_Tight({ subsets: ["latin"] });

// const noto = Noto_Sans({
// 	weight: ["300", "400", "600", "700"],
// 	subsets: ["latin"],
// 	variable: "--noto-sans",
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const lobster = Lobster({
	weight: ["400"],
	subsets: ["latin"],
	variable: "--lobster",
});

const great_vibes = Great_Vibes({
	weight: ["400"],
	subsets: ["latin"],
	variable: "--great_vibes",
});

const style_script = Style_Script({
	weight: ["400"],
	subsets: ["latin"],
	variable: "--style_script",
});

const heading_font = Calistoga({
	weight: ["400"],
	subsets: ["latin"],
	variable: "--heading_font",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} ${heading_font.variable} ${lobster.variable} 
			${great_vibes.variable} ${style_script.variable}  
			`}
			>
				{children}
			</body>
		</html>
	);
}
